### ISSUE TITLE
SIGQUIT on github.com/astaxie/beego/logs.(*BeeLogger).startLogger(0xc208107d40)

### ISSUE THREAD

**Issue by jbuberel** [astaxie/beego#1215]
I am attempting to run https://github.com/julienschmidt/go-http-routing-benchmark using both go14 and go15.

When running the benchmark, the `startLogger` method causes the application to terminate with SIGQUIT:

```
jbuberel@ubuntu:~/gosrc/src/github.com/julienschmidt/go-http-routing-benchmark$ go test -bench=. > go14bench.txt
#GithubAPI Routes: 203
   Ace: 53856 Bytes
   Bear: 83832 Bytes
   Beego: 165000 Bytes
   Bone: 97504 Bytes
   Denco: 36728 Bytes
   Echo: 74256 Bytes
   Gin: 52504 Bytes
   GocraftWeb: 89256 Bytes
   Goji: 47304 Bytes
   GoJsonRest: 134152 Bytes
   GoRestful: 1393304 Bytes
   GorillaMux: 1493088 Bytes
   HttpRouter: 37448 Bytes
   HttpTreeMux: 75056 Bytes
   Kocha: 785120 Bytes
   Macaron: 100072 Bytes
   Martini: 478272 Bytes
   Pat: 15832 Bytes
   Possum: 83408 Bytes
   R2router: 47104 Bytes
   Revel: 141088 Bytes
   Rivet: 110080 Bytes
   Tango: 51344 Bytes
   TigerTonic: 96048 Bytes
   Traffic: 1053488 Bytes
   Vulcan: 425584 Bytes

#GPlusAPI Routes: 13
   Ace: 3904 Bytes
   Bear: 7112 Bytes
   Beego: 11368 Bytes
   Bone: 6480 Bytes
   Denco: 3256 Bytes
   Echo: 5248 Bytes
   Gin: 3864 Bytes
   GocraftWeb: 7032 Bytes
   Goji: 2912 Bytes
   GoJsonRest: 11576 Bytes
   GoRestful: 87496 Bytes
   GorillaMux: 71056 Bytes
   HttpRouter: 2696 Bytes
   HttpTreeMux: 7184 Bytes
   Kocha: 128880 Bytes
   Macaron: 8072 Bytes
   Martini: 23936 Bytes
   Pat: 1448 Bytes
   Possum: 7248 Bytes
   R2router: 3928 Bytes
   Revel: 10768 Bytes
   Rivet: 7896 Bytes
   Tango: 4712 Bytes
   TigerTonic: 9408 Bytes
   Traffic: 49488 Bytes
   Vulcan: 25496 Bytes

#ParseAPI Routes: 26
   Ace: 7208 Bytes
   Bear: 12320 Bytes
   Beego: 21040 Bytes
   Bone: 11024 Bytes
   Denco: 4184 Bytes
   Echo: 8680 Bytes
   Gin: 6808 Bytes
   GocraftWeb: 12128 Bytes
   Goji: 5232 Bytes
   GoJsonRest: 14232 Bytes
   GoRestful: 125896 Bytes
   GorillaMux: 122136 Bytes
   HttpRouter: 4960 Bytes
   HttpTreeMux: 7680 Bytes
   Kocha: 181712 Bytes
   Macaron: 12984 Bytes
   Martini: 45952 Bytes
   Pat: 1976 Bytes
   Possum: 9200 Bytes
   R2router: 7056 Bytes
   Revel: 15488 Bytes
   Rivet: 13496 Bytes
   Tango: 8256 Bytes
   TigerTonic: 9840 Bytes
   Traffic: 93496 Bytes
   Vulcan: 44296 Bytes

#Static Routes: 157
   HttpServeMux: 17728 Bytes
   Ace: 33840 Bytes
   Bear: 30216 Bytes
   Beego: 103240 Bytes
   Bone: 38048 Bytes
   Denco: 9696 Bytes
   Echo: 39584 Bytes
   Gin: 30344 Bytes
   GocraftWeb: 51496 Bytes
   Goji: 27200 Bytes
   GoJsonRest: 136024 Bytes
   GoRestful: 906568 Bytes
   GorillaMux: 668512 Bytes
   HttpRouter: 21112 Bytes
   HttpTreeMux: 73352 Bytes
   Kocha: 115104 Bytes
   Macaron: 49512 Bytes
   Martini: 308784 Bytes
   Pat: 15704 Bytes
   Possum: 90848 Bytes
   R2router: 23712 Bytes
   Revel: 93392 Bytes
   Rivet: 42872 Bytes
   Tango: 25504 Bytes
   TigerTonic: 79904 Bytes
   Traffic: 624416 Bytes
   Vulcan: 368728 Bytes

SIGQUIT: quit
PC=0x442413

goroutine 5 [syscall]:
runtime.notetsleepg(0xfec6d8, 0x12993d97e, 0x0)
        /home/jbuberel/go/src/runtime/lock_futex.go:201 +0x52 fp=0xc208018f68 sp=0xc208018f40
runtime.timerproc()
        /home/jbuberel/go/src/runtime/time.go:207 +0xfa fp=0xc208018fe0 sp=0xc208018f68
runtime.goexit()
        /home/jbuberel/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fe8 sp=0xc208018fe0
created by runtime.addtimerLocked
        /home/jbuberel/go/src/runtime/time.go:113 +0x1ba

goroutine 1 [chan receive]:
testing.(*B).run(0xc20965f200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jbuberel/go/src/testing/benchmark.go:180 +0x67
testing.RunBenchmarks(0xd7d2b0, 0xfe7560, 0x1a1, 0x1a1)
        /home/jbuberel/go/src/testing/benchmark.go:312 +0x649
testing.(*M).Run(0xc208bac000, 0xff56a0)
        /home/jbuberel/go/src/testing/testing.go:494 +0x1a5
main.main()
        github.com/julienschmidt/go-http-routing-benchmark/_test/_testmain.go:886 +0x1d5

goroutine 305 [running]:
        goroutine running on other thread; stack unavailable
created by testing.(*B).run
        /home/jbuberel/go/src/testing/benchmark.go:179 +0x3e

goroutine 7 [chan receive, 9 minutes]:
github.com/astaxie/beego/logs.(*BeeLogger).startLogger(0xc208107d40)
        /home/jbuberel/gosrc/src/github.com/astaxie/beego/logs/log.go:197 +0x67
created by github.com/astaxie/beego/logs.NewLogger
        /home/jbuberel/gosrc/src/github.com/astaxie/beego/logs/log.go:114 +0xd7

rax     0xfffffffffffffffc
rbx     0x3b28b17e
rcx     0xffffffffffffffff
rdx     0x0
rdi     0xfec6d8
rsi     0x0
rbp     0xc208018f00
rsp     0xc208018ec0
r8      0x0
r9      0x0
r10     0xc208018ef8
r11     0x216
r12     0x1
r13     0x1
r14     0x2
r15     0xc208bd67e0
rip     0x442413
rflags  0x216
cs      0x33
fs      0x0
gs      0x0
```

A nearly identical error is produced when running with go15 (master):

```
jbuberel@ubuntu:~/gosrc/src/github.com/julienschmidt/go-http-routing-benchmark$ go test -bench=. > go14bench.txt
#GithubAPI Routes: 203
   Ace: 53856 Bytes
   Bear: 83832 Bytes
   Beego: 165000 Bytes
   Bone: 97504 Bytes
   Denco: 36728 Bytes
   Echo: 74256 Bytes
   Gin: 52504 Bytes
   GocraftWeb: 89256 Bytes
   Goji: 47304 Bytes
   GoJsonRest: 134152 Bytes
   GoRestful: 1393304 Bytes
   GorillaMux: 1493088 Bytes
   HttpRouter: 37448 Bytes
   HttpTreeMux: 75056 Bytes
   Kocha: 785120 Bytes
   Macaron: 100072 Bytes
   Martini: 478272 Bytes
   Pat: 15832 Bytes
   Possum: 83408 Bytes
   R2router: 47104 Bytes
   Revel: 141088 Bytes
   Rivet: 110080 Bytes
   Tango: 51344 Bytes
   TigerTonic: 96048 Bytes
   Traffic: 1053488 Bytes
   Vulcan: 425584 Bytes

#GPlusAPI Routes: 13
   Ace: 3904 Bytes
   Bear: 7112 Bytes
   Beego: 11368 Bytes
   Bone: 6480 Bytes
   Denco: 3256 Bytes
   Echo: 5248 Bytes
   Gin: 3864 Bytes
   GocraftWeb: 7032 Bytes
   Goji: 2912 Bytes
   GoJsonRest: 11576 Bytes
   GoRestful: 87496 Bytes
   GorillaMux: 71056 Bytes
   HttpRouter: 2696 Bytes
   HttpTreeMux: 7184 Bytes
   Kocha: 128880 Bytes
   Macaron: 8072 Bytes
   Martini: 23936 Bytes
   Pat: 1448 Bytes
   Possum: 7248 Bytes
   R2router: 3928 Bytes
   Revel: 10768 Bytes
   Rivet: 7896 Bytes
   Tango: 4712 Bytes
   TigerTonic: 9408 Bytes
   Traffic: 49488 Bytes
   Vulcan: 25496 Bytes

#ParseAPI Routes: 26
   Ace: 7208 Bytes
   Bear: 12320 Bytes
   Beego: 21040 Bytes
   Bone: 11024 Bytes
   Denco: 4184 Bytes
   Echo: 8680 Bytes
   Gin: 6808 Bytes
   GocraftWeb: 12128 Bytes
   Goji: 5232 Bytes
   GoJsonRest: 14232 Bytes
   GoRestful: 125896 Bytes
   GorillaMux: 122136 Bytes
   HttpRouter: 4960 Bytes
   HttpTreeMux: 7680 Bytes
   Kocha: 181712 Bytes
   Macaron: 12984 Bytes
   Martini: 45952 Bytes
   Pat: 1976 Bytes
   Possum: 9200 Bytes
   R2router: 7056 Bytes
   Revel: 15488 Bytes
   Rivet: 13496 Bytes
   Tango: 8256 Bytes
   TigerTonic: 9840 Bytes
   Traffic: 93496 Bytes
   Vulcan: 44296 Bytes

#Static Routes: 157
   HttpServeMux: 17728 Bytes
   Ace: 33840 Bytes
   Bear: 30216 Bytes
   Beego: 103240 Bytes
   Bone: 38048 Bytes
   Denco: 9696 Bytes
   Echo: 39584 Bytes
   Gin: 30344 Bytes
   GocraftWeb: 51496 Bytes
   Goji: 27200 Bytes
   GoJsonRest: 136024 Bytes
   GoRestful: 906568 Bytes
   GorillaMux: 668512 Bytes
   HttpRouter: 21112 Bytes
   HttpTreeMux: 73352 Bytes
   Kocha: 115104 Bytes
   Macaron: 49512 Bytes
   Martini: 308784 Bytes
   Pat: 15704 Bytes
   Possum: 90848 Bytes
   R2router: 23712 Bytes
   Revel: 93392 Bytes
   Rivet: 42872 Bytes
   Tango: 25504 Bytes
   TigerTonic: 79904 Bytes
   Traffic: 624416 Bytes
   Vulcan: 368728 Bytes

SIGQUIT: quit
PC=0x442413

goroutine 5 [syscall]:
runtime.notetsleepg(0xfec6d8, 0x12993d97e, 0x0)
        /home/jbuberel/go/src/runtime/lock_futex.go:201 +0x52 fp=0xc208018f68 sp=0xc208018f40
runtime.timerproc()
        /home/jbuberel/go/src/runtime/time.go:207 +0xfa fp=0xc208018fe0 sp=0xc208018f68
runtime.goexit()
        /home/jbuberel/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fe8 sp=0xc208018fe0
created by runtime.addtimerLocked
        /home/jbuberel/go/src/runtime/time.go:113 +0x1ba

goroutine 1 [chan receive]:
testing.(*B).run(0xc20965f200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jbuberel/go/src/testing/benchmark.go:180 +0x67
testing.RunBenchmarks(0xd7d2b0, 0xfe7560, 0x1a1, 0x1a1)
        /home/jbuberel/go/src/testing/benchmark.go:312 +0x649
testing.(*M).Run(0xc208bac000, 0xff56a0)
        /home/jbuberel/go/src/testing/testing.go:494 +0x1a5
main.main()
        github.com/julienschmidt/go-http-routing-benchmark/_test/_testmain.go:886 +0x1d5

goroutine 305 [running]:
        goroutine running on other thread; stack unavailable
created by testing.(*B).run
        /home/jbuberel/go/src/testing/benchmark.go:179 +0x3e

goroutine 7 [chan receive, 9 minutes]:
github.com/astaxie/beego/logs.(*BeeLogger).startLogger(0xc208107d40)
        /home/jbuberel/gosrc/src/github.com/astaxie/beego/logs/log.go:197 +0x67
created by github.com/astaxie/beego/logs.NewLogger
        /home/jbuberel/gosrc/src/github.com/astaxie/beego/logs/log.go:114 +0xd7

rax     0xfffffffffffffffc
rbx     0x3b28b17e
rcx     0xffffffffffffffff
rdx     0x0
rdi     0xfec6d8
rsi     0x0
rbp     0xc208018f00
rsp     0xc208018ec0
r8      0x0
r9      0x0
r10     0xc208018ef8
r11     0x216
r12     0x1
r13     0x1
r14     0x2
r15     0xc208bd67e0
rip     0x442413
rflags  0x216
cs      0x33
fs      0x0
gs      0x0
```

**Comment by jbuberel** [comment]
This appears to be caused by an out of memory condition, so closing.
