### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by mohong122** [astaxie/beego#1509]
启用定时任务后，一段时间就会出现这个

``` go

panic: sync: negative WaitGroup counter

goroutine 31991 [running]:
sync.(*WaitGroup).Add(0xc820363468, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:70 +0xd0
sync.(*WaitGroup).Done(0xc820363468)
	/usr/local/go/src/sync/waitgroup.go:95 +0x2a
github.com/astaxie/beego/grace.graceConn.Close(0x7f8566e78108, 0xc820208210, 0xc820363440, 0x0, 0x0)
	/data/gopath/src/github.com/astaxie/beego/grace/conn.go:11 +0x39
github.com/astaxie/beego/grace.(*graceConn).Close(0xc8204e3f80, 0x0, 0x0)
	<autogenerated>:22 +0xad
net/http.(*conn).close(0xc820303b80)
	/usr/local/go/src/net/http/server.go:1228 +0x4c
net/http.(*conn).serve.func1(0xc820303b80, 0x7f855f7c3b68, 0xc8204e3f80)
	/usr/local/go/src/net/http/server.go:1291 +0x294
net/http.(*conn).serve(0xc820303b80)
	/usr/local/go/src/net/http/server.go:1374 +0x884
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 1 [chan receive, 85 minutes]:
github.com/astaxie/beego.(*App).Run(0xc8200754c0)
	/data/gopath/src/github.com/astaxie/beego/app.go:171 +0x33d
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
	/data/gopath/src/github.com/astaxie/beego/beego.go:277 +0x17d
main.main()
	/data/gopath/src/onetravel/main.go:20 +0xff

goroutine 17 [syscall, 85 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [syscall, 85 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 21 [chan receive, 85 minutes]:
database/sql.(*DB).connectionOpener(0xc8201c28c0)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 34 [chan receive, 85 minutes]:
database/sql.(*DB).connectionOpener(0xc82036aaa0)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 35 [select]:
github.com/astaxie/beego/toolbox.run()
	/data/gopath/src/github.com/astaxie/beego/toolbox/task.go:413 +0x685
created by github.com/astaxie/beego/toolbox.StartTask
	/data/gopath/src/github.com/astaxie/beego/toolbox/task.go:393 +0x32

goroutine 36 [IO wait]:
net.runtime_pollWait(0x7f856482c248, 0x72, 0xc8200740b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8204967d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204967d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820496770, 0x0, 0x7f855f7c3b40, 0xc8204e3fc0)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8203de0d0, 0xc820303bc8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
github.com/astaxie/beego/grace.(*graceListener).Accept(0xc820494f90, 0x0, 0x0, 0x0, 0x0)
	/data/gopath/src/github.com/astaxie/beego/grace/listener.go:32 +0x70
net/http.(*Server).Serve(0xc820072420, 0x7f855f7c3b08, 0xc820494f90, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/astaxie/beego/grace.(*graceServer).Serve(0xc820363440, 0x0, 0x0)
	/data/gopath/src/github.com/astaxie/beego/grace/server.go:35 +0x62
github.com/astaxie/beego/grace.(*graceServer).ListenAndServe(0xc820363440, 0x0, 0x0)
	/data/gopath/src/github.com/astaxie/beego/grace/server.go:74 +0x507
github.com/astaxie/beego.(*App).Run.func2(0xc820465570, 0xc8200754c0, 0xc820496700)
	/data/gopath/src/github.com/astaxie/beego/app.go:109 +0xcf
created by github.com/astaxie/beego.(*App).Run
	/data/gopath/src/github.com/astaxie/beego/app.go:115 +0x823

goroutine 37 [chan receive, 85 minutes]:
github.com/astaxie/beego/grace.(*graceServer).handleSignals(0xc820363440)
	/data/gopath/src/github.com/astaxie/beego/grace/server.go:172 +0x2b1
created by github.com/astaxie/beego/grace.(*graceServer).ListenAndServe
	/data/gopath/src/github.com/astaxie/beego/grace/server.go:51 +0x9e

goroutine 38 [chan receive, 85 minutes]:
github.com/astaxie/beego/grace.newGraceListener.func1(0xc8203de0d8)
	/data/gopath/src/github.com/astaxie/beego/grace/listener.go:24 +0x4e
created by github.com/astaxie/beego/grace.newGraceListener
	/data/gopath/src/github.com/astaxie/beego/grace/listener.go:27 +0x119

goroutine 39 [select, 85 minutes, locked to thread]:
runtime.gopark(0xcc1960, 0xc8203ebf28, 0xb84af8, 0x6, 0x42dd18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc8203ebf28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc8203ebf28)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 31834 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f856482b708, 0x72, 0xc8200740b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201c7e90, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201c7e90, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201c7e30, 0xc8203ff000, 0x1000, 0x1000, 0x0, 0x7f8564826028, 0xc8200740b0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200963a0, 0xc8203ff000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f8566e781b0, 0xc8200963a0, 0xc8200eacb8, 0xc8203ff000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8207049a0, 0xc8203ff000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820362c60)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820362c60, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200eac60)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 31969 [select]:
net/http.(*persistConn).writeLoop(0xc8203022c0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 31908 [IO wait]:
net.runtime_pollWait(0x7f85648323b0, 0x72, 0xc8200740b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203c3090, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203c3090, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203c3030, 0xc82016b000, 0x1000, 0x1000, 0x0, 0x7f8564826028, 0xc8200740b0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8202f0208, 0xc82016b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f8566e781b0, 0xc8202f0208, 0xc8200eba78, 0xc82016b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8202a6c40, 0xc82016b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8205f2b40)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8205f2b40, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200eba20)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 31909 [select]:
net/http.(*persistConn).writeLoop(0xc8200eba20)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 31968 [IO wait]:
net.runtime_pollWait(0x7f856482f138, 0x72, 0xc8200740b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820886c30, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820886c30, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820886bd0, 0xc820367000, 0x1000, 0x1000, 0x0, 0x7f8564826028, 0xc8200740b0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820208148, 0xc820367000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f8566e781b0, 0xc820208148, 0xc820302318, 0xc820367000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8204ca840, 0xc820367000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8205eafc0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8205eafc0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8203022c0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 31835 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8200eac60)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 31875 [IO wait]:
net.runtime_pollWait(0x7f856482ea78, 0x72, 0xc8200740b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201c6530, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201c6530, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201c64d0, 0xc820772000, 0x1000, 0x1000, 0x0, 0x7f8564826028, 0xc8200740b0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820208128, 0xc820772000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f8566e781b0, 0xc820208128, 0xc8200ea528, 0xc820772000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820270a60, 0xc820772000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8201a3140)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8201a3140, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200ea4d0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 31876 [select]:
net/http.(*persistConn).writeLoop(0xc8200ea4d0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d
```

**Comment by astaxie** [comment]
#1232 类似
