### ISSUE TITLE
Concurrent map read and map write

### ISSUE THREAD

**Issue by novikk** [astaxie/beego#1973]
1. What version of Go and beego are you using (`bee version`)?
```
bee   :1.4.1
beego :1.6.0
Go    :go version go1.6 windows/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOEXE=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=linux
set GOPATH=D:\dev\GoPath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-fPIC -m64 -fmessage-length=0
set CXX=g++
set CGO_ENABLED=0
```

3. What did you do?
Can't reproduce. Happened randomly in production, but from the stack trace it seems like it is a problem with beego. 

4. What did you expect to see?
Home page

5. What did you see instead?
```
fatal error: concurrent map read and map write

goroutine 890180 [running]:
runtime.throw(0xc9d660, 0x21)
        C:/Go/src/runtime/panic.go:530 +0x90 fp=0xc8204e1458 sp=0xc8204e1440
runtime.mapaccess1_faststr(0x9cb6e0, 0xc82013c1e0, 0xc048f0, 0x9, 0xc8204a7210)
        C:/Go/src/runtime/hashmap_fast.go:202 +0x5b fp=0xc8204e14b8 sp=0xc8204e1458
github.com/astaxie/beego.(*Controller).RenderBytes(0xc827b88480, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/dev/GoPath/src/github.com/astaxie/beego/controller.go:223 +0x563 fp=0xc8204e1760 sp=0xc8204e14b8
github.com/astaxie/beego.(*Controller).Render(0xc827b88480, 0x0, 0x0)
        D:/dev/GoPath/src/github.com/astaxie/beego/controller.go:183 +0x4e fp=0xc8204e17c0 sp=0xc8204e1760
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc82013c2d0, 0x6aa053fd21e0, 0xc8203436c0, 0xc82029d0a0)
        D:/dev/GoPath/src/github.com/astaxie/beego/router.go:784 +0x1d7c fp=0xc8204e1b60 sp=0xc8204e17c0
net/http.serverHandler.ServeHTTP(0xc820088180, 0x6aa053fd21e0, 0xc8203436c0, 0xc82029d0a0)
        C:/Go/src/net/http/server.go:2081 +0x19e fp=0xc8204e1bc0 sp=0xc8204e1b60
net/http.(*conn).serve(0xc8207dd480)
        C:/Go/src/net/http/server.go:1472 +0xf2e fp=0xc8204e1f88 sp=0xc8204e1bc0
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8204e1f90 sp=0xc8204e1f88
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2137 +0x44e
```

**Comment by ZichaoHe** [comment]
I have the same problem with you.
Beego create a new go-routine to deal with the request.If there is a global value used by different go-routines.Maybe a "concurrent map read and map write" error will be bappen randomly.A lock should be used to portect the value.
I think this problem may not due to the Beego.See "net/http" package for detail.

**Comment by novikk** [comment]
@ZichaoHe I don't have any global variable. It has something to do with the "BeeTemplates" variable I think

**Comment by JessonChan** [comment]
@novikk maybe this pr https://github.com/astaxie/beego/pull/1752
