### ISSUE TITLE
failed to go get

### ISSUE THREAD

**Issue by wilsonloo** [astaxie/beego#1981]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/go/src"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
// # go get -v github.com/astaxie/beego
github.com/astaxie/beego (download)
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x93d400, 0xc82000e0d0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.vendoredImportPath(0xc82047b400, 0xc82045aea1, 0x20, 0x0, 0x0)
        /usr/local/go/src/cmd/go/pkg.go:466 +0x713
main.loadImport(0xc82045aea1, 0x20, 0xc820460400, 0x39, 0xc82047b400, 0xc82013b800, 0xc82045b0b0, 0x1, 0x1, 0x1, ...)
        /usr/local/go/src/cmd/go/pkg.go:336 +0xe52
main.(*Package).load(0xc82047b400, 0xc82013b800, 0xc820299180, 0x0, 0x0, 0x4)
        /usr/local/go/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0xc82023b711, 0x20, 0xc8201778c0, 0x2e, 0xc820183800, 0xc82013b800, 0xc820167680, 0x8, 0x8, 0x1, ...)
        /usr/local/go/src/cmd/go/pkg.go:377 +0x84e
main.(*Package).load(0xc820183800, 0xc82013b800, 0xc82018f500, 0x0, 0x0, 0xc)
        /usr/local/go/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0x7ffcde2a476c, 0x18, 0xc8200100e4, 0x11, 0x0, 0xc82013b800, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/cmd/go/pkg.go:377 +0x84e
main.loadPackage(0x7ffcde2a476c, 0x18, 0xc82013b800, 0x0)
        /usr/local/go/src/cmd/go/pkg.go:1639 +0x13d8
main.download.func1(0x7ffcde2a476c, 0x18, 0x0, 0x18)
        /usr/local/go/src/cmd/go/get.go:191 +0x43
main.download(0x7ffcde2a476c, 0x18, 0x0, 0xc82013b800, 0x0)
        /usr/local/go/src/cmd/go/get.go:279 +0x1b9e
main.runGet(0xc8a1a0, 0xc82000a1f0, 0x1, 0x1)
        /usr/local/go/src/cmd/go/get.go:107 +0x1e5
main.main()
        /usr/local/go/src/cmd/go/main.go:181 +0x783

**Comment by wilsonloo** [comment]
well, I fix it in another way: reinstall it myself using the https://github.com/astaxie/beego.git; but not 
go get github.com/astaxie/beego
