### ISSUE TITLE
beego.AppConfig.Strings can not get global config variables

### ISSUE THREAD

**Issue by ZachBergh** [astaxie/beego#2027]
### false app.conf:
```
runmode = dev

strings_conf = val1;val2;val3

[dev]
...

[prod]
...
```
`beego.AppConfig.Strings("strings_conf")` is `[]`

### right app.conf: 
```
runmode = dev

[dev]
strings_conf = val1;val2;val3
...

[prod]
...
```
`beego.AppConfig.Strings("strings_conf")` is `["val1","val2","val3"]`

This is different from last version, is this a new feature or bug?

**Comment by astaxie** [comment]
@youngsterxyf could you help to check this issue?

**Comment by youngsterxyf** [comment]
@ZachBergh which version of beego ?

**Comment by ZachBergh** [comment]
@youngsterxyf The newest version.

**Comment by ZachBergh** [comment]
@youngsterxyf 

### code

```
// app.conf
runmode = dev
strings_conf = val1;val2;val3


//  main.go
package main

import(
    "github.com/astaxie/beego"
)

func main() {
    beego.AppConfig.Strings("strings_conf")
    beego.Run()
}

```


### error
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/astaxie/beego.(*beegoAppConfig).Strings(0xc20800a7d0, 0x54c110, 0xc, 0x0, 0x0, 0x0)
	/Users/ZachBergh/Code/Golang/src/gitlab.aeris.cn/aerisgo/test/Godeps/_workspace/src/github.com/astaxie/beego/config.go:356 +0x19c
main.main()
	/Users/ZachBergh/Code/Golang/src/gitlab.aeris.cn/aerisgo/test/main.go:8 +0x3d

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [runnable]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35
```

**Comment by youngsterxyf** [comment]
@ZachBergh @astaxie yes， it is a bug. i will fix it.

**Comment by youngsterxyf** [comment]
@ZachBergh @astaxie @JessonChan he has fixed it in commit https://github.com/astaxie/beego/commit/959b9a5a580e2e232b92680f640b1865bf3af24d

**Comment by ZachBergh** [comment]
@youngsterxyf @astaxie Thank you guys.
