### ISSUE TITLE
PANIC:  logger.formatTimeHeader panics on dates prior to 2000

### ISSUE THREAD

**Issue by mmindenhall** [astaxie/beego#2090]
Our application runs on an IoT gateway device, and is started automatically via an init script.  Sometimes our application starts before ntpd updated the system time, so the date is read as something prior to 2000 (probably 1970-01-01), and we see this panic:

```
panic: runtime error: index out of range

goroutine 294 [running]:
panic(0xa23e90, 0x1130a030)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x33c
github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs.formatTimeHeader(0xafff3abb, 0xe, 0x34cb4740, 0x1013340, 0x0, 0x0, 0x0, 0xad0d56)
	/Users/mmindenhall/golang/src/github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs/logger.go:62 +0x104
github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs.(*logWriter).println(0x1155c290, 0xafff3abb, 0xe, 0x34cb4740, 0x1013340, 0x115623c0, 0x2c)
	/Users/mmindenhall/golang/src/github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs/logger.go:34 +0x4c
github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs.(*consoleWriter).WriteMsg(0x1155c2a0, 0xafff3abb, 0xe, 0x34cb4740, 0x1013340, 0x115623c0, 0x2c, 0x6
, 0x0, 0x0)
	/Users/mmindenhall/golang/src/github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs/console.go:85 +0xd8
github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs.(*BeeLogger).writeToLoggers(0x114d60a0, 0xafff3abb, 0xe, 0x34cb4740, 0x1013340, 0x11562390, 0x21, 0
x6)
	/Users/mmindenhall/golang/src/github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs/log.go:234 +0xd4
github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs.(*BeeLogger).writeMsg(0x114d60a0, 0x6, 0x11562390, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/mmindenhall/golang/src/github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs/log.go:289 +0x398
github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs.(*BeeLogger).Info(0x114d60a0, 0x1156ffc0, 0x1d, 0x0, 0x0, 0x0)
	/Users/mmindenhall/golang/src/github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs/log.go:416 +0x60
github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs.Info(0x9f6420, 0x11641a20, 0x11337f50, 0x1, 0x1)
	/Users/mmindenhall/golang/src/github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/logs/log.go:597 +0x74
github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego.(*adminApp).Run(0x11474d88)
	/Users/mmindenhall/golang/src/github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/admin.go:390 +0x30c
created by github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego.registerAdmin
	/Users/mmindenhall/golang/src/github.com/MachineShop-IOT/edge/vendor/github.com/astaxie/beego/hooks.go:87 +0x50
```
&nbsp;

Is there some reason for formatting the date manually rather than via `time.Format`?  This code works, and doesn't panic for dates prior to 2000:

```go
func formatTimeHeader(when time.Time) ([]byte, int) {
	_, _, d := when.Date()
	s := when.Format("2006/01/02 15:04:05 ")
	return []byte(s), d
}
```

**Comment by astaxie** [comment]
@mmindenhall it should be fixed in master now. Why we didn't use the Format as it's too slow. This function will have 300 times fast.  I update it here. it should works. https://github.com/astaxie/beego/commit/bed1d9bd27d2209c7d10d8d5d0d420b4049002e0
