### ISSUE TITLE
Error with bee automated documnet generation!

### ISSUE THREAD

**Issue by skptl** [astaxie/beego#2163]
```
├── Bee       : 1.5.1
├── Beego     : 1.7.0
├── GoVersion : go1.6.2
├── GOOS      : linux
├── GOARCH    : amd64
├── Compiler  : gc
└── Date      : Saturday, 17 Sep 2016
```
As soon I have a struct with `map[string]string` as an object in body or response. The document generation fails with the following stack trace. It is reproducible on the template project generated with `bee api test`

Following is the stack trace:
``` 
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x9923a0, 0xc82000e0f0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.parseObject(0xc8201e76d0, 0xc8201ec780, 0xb, 0xc82016c6f0, 0xc82016c768, 0xc82018be30)
        /home/abc/golang/src/github.com/beego/bee/g_docs.go:667 +0x1173
main.getModel(0xc82019c880, 0x12, 0xc82019c880, 0x6, 0xc82019c887, 0xb, 0x0, 0x0, 0xc8201ec780, 0xb, ...)
        /home/abc/golang/src/github.com/beego/bee/g_docs.go:615 +0x638
main.parserComments(0xc82018e0e0, 0xc82017f680, 0x7, 0xc820198d50, 0xe, 0xc820013701, 0x30, 0x0, 0x0)
        /home/abc/golang/src/github.com/beego/bee/g_docs.go:441 +0x2438
main.analisyscontrollerPkg(0x0, 0x0, 0xc820013701, 0x30)
        /home/abc/golang/src/github.com/beego/bee/g_docs.go:290 +0xa43
main.generateDocs(0xc8200140a4, 0x3d)

        /home/abc/golang/src/github.com/beego/bee/g_docs.go:100 +0x571
main.generateCode(0xd2e7c0, 0xc82000a2f0, 0x1, 0x1, 0x0)
        /home/abc/golang/src/github.com/beego/bee/g.go:129 +0x405
main.main()
        /home/abc/golang/src/github.com/beego/bee/bee.go:115 +0x376
```

**Comment by skptl** [comment]
Any idea what is happening?

**Comment by astaxie** [comment]
@skptl I will check today. Sorry for the later reply.

**Comment by astaxie** [comment]
@skptl could you provide the example cooments?

**Comment by skptl** [comment]
Here is the modified User struct for the generated project:
```
type User struct {
	Id       string
	Username string
	Password string
	Profile  Profile
	BreakingMap map[string]string // Breaks as soon as I add this
}
```

Comment for the controller:
```
// @Param	body		body 	models.User	true		"body for user content"
```

**Comment by astaxie** [comment]
fix in beego/bee develop branch now

**Comment by astaxie** [comment]
https://github.com/beego/bee/commit/29c9e1bab765bd1b360edfbc1e3a6d8a50571206
