### ISSUE TITLE
开启热部署后,并发请求一些接口导致服务崩溃

### ISSUE THREAD

**Issue by XavierMoon** [astaxie/beego#2166]
同时开启了热部署,gzip压缩,压缩级别9.开启了session
~~不清楚是否为开启热部署后导致的问题.~~
*已经确认是因为开启热部署导致的问题.*
  #2133 *也提到了这个问题.*
报错后程序异常退出.
报错信息如下
```
panic: sync: negative WaitGroup counter

goroutine 9 [running]:
panic(0x8ab680, 0xc42089c000)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
sync.(*WaitGroup).Add(0xc4204a8328, 0x1)
	/usr/local/go/src/sync/waitgroup.go:75 +0x1fe
github.com/astaxie/beego/grace.(*graceListener).Accept(0xc420015f80, 0x9aecc0, 0xc420010600, 0xbabd20, 0xc42035e330)
	/data/golang/src/github.com/astaxie/beego/grace/listener.go:45 +0x138
net/http.(*Server).Serve(0xc4201ec000, 0xbaa320, 0xc420015f80, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2273 +0x1ce
github.com/astaxie/beego/grace.(*Server).Serve(0xc4204a8300, 0x2, 0x2)
	/data/golang/src/github.com/astaxie/beego/grace/server.go:36 +0x4b
github.com/astaxie/beego/grace.(*Server).ListenAndServe(0xc4204a8300, 0x6, 0xba5260)
	/data/golang/src/github.com/astaxie/beego/grace/server.go:75 +0x299
github.com/astaxie/beego.(*App).Run.func2(0xc42000c610, 0x6, 0xc42000d760, 0xc42005a930)
	/data/golang/src/github.com/astaxie/beego/app.go:130 +0xbf
created by github.com/astaxie/beego.(*App).Run
	/data/golang/src/github.com/astaxie/beego/app.go:135 +0x885
[1]  + 17304 exit 2
```

**Comment by XavierMoon** [comment]
#2133

**Comment by astaxie** [comment]
please follow the issue template
