### ISSUE TITLE
Can't build after Mac OS Sierra upgrade

### ISSUE THREAD

**Issue by jjamaral** [astaxie/beego#2198]
1. What version of Go and beego are you using (`bee version`)?
```
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.5.0

├── Beego     : 1.7.0
├── GoVersion : go1.6.3
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/jjamaral/go
├── GOROOT    : /usr/local/Cellar/go/1.6.3/libexec
├── Compiler  : gc
└── Date      : Thursday, 29 Sep 2016
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jjamaral/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.3/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
Just upgraded the Mac OS to Sierra. And then when I run "bee run" command, its broken. Can't build.

4. What did you expect to see?
Application build successfully.

5. What did you see instead?
Error:
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x63716de7c4 pc=0x9c73b]
```

Full error detail:
```
2016/09/29 11:26:25 [INFO] Start building...
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.5.0
2016/09/29 11:26:25 [SUCC] Docs successfully generated!
2016/09/29 11:26:25 ============== generate docs ===================
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x63716de7c4 pc=0x9c73b]

runtime stack:
runtime.throw(0x689a00, 0x2a)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x894e80)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x894e80, 0x1, 0x3, 0x9f9320)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbff8e8)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x894e80, 0x1, 0x10000000003, 0x9c3df)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x8962a0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x8962a0, 0xc82020ba70)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x96d000, 0x3, 0xc82020ba40)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x88ff00)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc820b78210 sp=0xc820b78208
runtime.mallocgc(0x20, 0x544880, 0x0, 0x1)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc820b782e8 sp=0xc820b78210
runtime.newobject(0x544880, 0x938)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:781 +0x42 fp=0xc820b78310 sp=0xc820b782e8
go/parser.(*parser).consumeComment(0xc8210ded80, 0x938, 0x1)
	/usr/local/Cellar/go/1.6.3/libexec/src/go/parser/parser.go:274 +0xdc fp=0xc820b78348 sp=0xc820b78310
go/parser.(*parser).consumeCommentGroup(0xc8210ded80, 0x1, 0x0, 0x1)
	/usr/local/Cellar/go/1.6.3/libexec/src/go/parser/parser.go:290 +0xc4 fp=0xc820b783c8 sp=0xc820b78348
go/parser.(*parser).next(0xc8210ded80)
	/usr/local/Cellar/go/1.6.3/libexec/src/go/parser/parser.go:340 +0x15d fp=0xc820b78410 sp=0xc820b783c8
go/parser.(*parser).init(0xc8210ded80, 0xc8210f6f00, 0xc8210f8910, 0x42, 0xc8210d9400, 0x16b, 0x200, 0x6)
	/usr/local/Cellar/go/1.6.3/libexec/src/go/parser/parser.go:85 +0x14b fp=0xc820b78460 sp=0xc820b78410
go/parser.ParseFile(0xc8210f6f00, 0xc8210f8910, 0x42, 0x4533c0, 0xc8210effc0, 0x6, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/go/parser/interface.go:116 +0x199 fp=0xc820b784d0 sp=0xc820b78460
go/build.(*Context).Import(0x88faa0, 0xc82109d9a1, 0xd, 0xc8210c0f40, 0x37, 0x4, 0xc8210dc400, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/go/build/build.go:754 +0x26af fp=0xc820b79030 sp=0xc820b784d0
main.loadImport(0xc82109d9a1, 0xd, 0xc8210c0f40, 0x37, 0xc8210c2400, 0xc820b7b740, 0xc8210ca720, 0x1, 0x1, 0x1, ...)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/pkg.go:368 +0x6f0 fp=0xc820b79240 sp=0xc820b79030
main.(*Package).load(0xc8210c2400, 0xc820b7b740, 0xc8210c6000, 0x0, 0x0, 0x4)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/pkg.go:953 +0x4397 fp=0xc820b79b38 sp=0xc820b79240
main.loadImport(0xc8201a5dd1, 0x20, 0xc820182db0, 0x2f, 0xc820173000, 0xc820b7b740, 0xc8201c8460, 0x2, 0x2, 0x1, ...)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/pkg.go:377 +0x84e fp=0xc820b79d48 sp=0xc820b79b38
main.(*Package).load(0xc820173000, 0xc820b7b740, 0xc82016bc00, 0x0, 0x0, 0x4)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/pkg.go:953 +0x4397 fp=0xc820b7a640 sp=0xc820b79d48
main.loadImport(0xc82017ca61, 0x18, 0xc82014dc20, 0x23, 0xc820172c00, 0xc820b7b740, 0xc8201825d0, 0x1, 0x1, 0x1, ...)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/pkg.go:377 +0x84e fp=0xc820b7a850 sp=0xc820b7a640
main.(*Package).load(0xc820172c00, 0xc820b7b740, 0xc82016b880, 0x0, 0x0, 0xc)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/pkg.go:953 +0x4397 fp=0xc820b7b148 sp=0xc820b7a850
main.loadImport(0xc82014d817, 0xc, 0xc820014034, 0x23, 0x0, 0xc820b7b740, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/pkg.go:377 +0x84e fp=0xc820b7b358 sp=0xc820b7b148
main.loadPackage(0xc82014d817, 0xc, 0xc820b7b740, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/pkg.go:1639 +0x13d8 fp=0xc820b7b668 sp=0xc820b7b358
main.packagesAndErrors(0xc82015d980, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/pkg.go:1684 +0x531 fp=0xc820b7b8f8 sp=0xc820b7b668
main.packagesForBuild(0xc82000a2b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/pkg.go:1700 +0x82 fp=0xc820b7ba58 sp=0xc820b7b8f8
main.runBuild(0x888ae0, 0xc82000a2b0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/build.go:442 +0x8d fp=0xc820b7bc30 sp=0xc820b7ba58
main.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/cmd/go/main.go:181 +0x783 fp=0xc820b7bf20 sp=0xc820b7bc30
runtime.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc820b7bf70 sp=0xc820b7bf20
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820b7bf78 sp=0xc820b7bf70

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:28 +0x37
2016/09/29 11:26:26 [ERRO] ============== Build failed ===================

```

Any help please?

Thanks in advance!

**Comment by astaxie** [comment]
it's the new Mac OS issue. You need to upgrade the Go to the latest version https://github.com/golang/go/issues/16331

**Comment by XuHuaiyu** [comment]
@jjamaral 
hi, I just meet the same problem, have you solved this issue? how?
