### ISSUE TITLE
orm m2m rel_through problems

### ISSUE THREAD

**Issue by DavadDi** [astaxie/beego#2324]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

user and role are m2m relationship, I want to define the rel_through self_define table, **which adds one column of update time**.

> type User struct {
>	Id    uint64
>	Name  string  `orm:"size(64)"`
>	Roles []*Role `orm:"rel(m2m);rel_through(orm_m2m/model.UserRoles)"`
>}

> type Role struct {
>	Id   uint64
>	Name string `orm:"size(64)"`
>
>	Users []*User `orm:"reverse(many);rel_through(orm_m2m/model.UserRoles)"`
 >}

 > type UserRoles struct {
>	Id    int       `orm:"column(id)"`
>	User  *User     `orm:"rel(fk);column(user_id)"`
>	Role  *Role     `orm:"rel(fk);column(role_id)"`
>	** Added time.Time `orm:"auto_now;type(datetime)"` **
 >}

>  func init() {
	orm.RegisterModel(new(UserRoles))
	orm.RegisterModel(new(User))
	orm.RegisterModel(new(Role))
 }

4. What did you expect to see?

relationship table add column can add time auto now.

5. What did you see instead?

`
[panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
panic(0x2df260, 0xc8200acd90)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
strings.Repeat(0xc8200d58e0, 0xb, 0xffffffffffffffff, 0x0, 0x0)
	/usr/local/go/src/strings/strings.go:427 +0x5f
github.com/astaxie/beego/orm.(*dbBase).InsertValue(0xc82000a380, 0x700198, 0xc8200a8780, 0xc820016820, 0x1, 0xc8200a8800, 0x3, 0x4, 0xc8200a2a60, 0x2, ...)
	/Users/davaddi/golang/src/github.com/astaxie/beego/orm/db.go:435 +0x3f0
github.com/astaxie/beego/orm.(*queryM2M).Add(0xc8200a87c0, 0xc8200acd10, 0x1, 0x1, 0x5, 0x0, 0x0)](url)
`
[Full code](https://github.com/DavadDi/go_study/commit/59b010684821587d72ffc4e1d554ad814cf22a07)

**Comment by DavadDi** [comment]
[Full code](https://github.com/DavadDi/go_study/tree/master/src/orm_m2m)

**Comment by DavadDi** [comment]
because rel_through table  add extra field, so should add param to m2m.Add, like:

`num, err := m2m.Add(role, time.Now().Format("2006-01-02 15:04:05"))`

[fixed code](https://github.com/DavadDi/go_study/commit/b4daab77cc9a438065314fb87c68e7f1a1a4d484)
