### ISSUE TITLE
ErrorController can not ServeJSON

### ISSUE THREAD

**Issue by modood** [astaxie/beego#2375]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
├── Beego     : 1.7.2
├── GoVersion : go1.7
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /home/mwn/.gvm/pkgsets/go1.7/global
├── GOROOT    : /home/mwn/.gvm/gos/go1.7
├── Compiler  : gc
└── Date      : Tuesday, 10 Jan 2017
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mwn/.gvm/pkgsets/go1.7/global"
GORACE=""
GOROOT="/home/mwn/.gvm/gos/go1.7"
GOTOOLDIR="/home/mwn/.gvm/gos/go1.7/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build014834403=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```
func (this *ErrorController) ErrorTest() { 
  this.Data["json"] = map[string]string{"foo": "bar"} 
  this.ServeJSON()         
}
```

4. What did you expect to see?
我期待返回 JSON，但是无论怎么处理，都无法设置 `Content-Type:application/json`，始终会去寻找模板文件。看了一篇文章：[beego中的异常处理流程](http://www.th7.cn/Program/go/201601/748331.shtml) 解释了这个问题，但是我想知道怎么解决呢

5. What did you see instead?

```
2017/01/10 12:08:06 [server.go:2315] [HTTP] http: panic serving 127.0.0.1:47530: can't find templatefile in the path:errorcontroller/errortest.tpl
goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc4201a8900)
        /home/mwn/.gvm/gos/go1.7/src/net/http/server.go:1491 +0x12a
panic(0x8adc40, 0xc42021ed70)
        /home/mwn/.gvm/gos/go1.7/src/runtime/panic.go:458 +0x243
```

**Comment by astaxie** [comment]
You can turn off the render in ErrorController
`this.EnableRender =false`
