### ISSUE TITLE
关于设置了 RecoverPanic = true 依然报Panic这个问题

### ISSUE THREAD

**Issue by icowan** [astaxie/beego#2994]
# 异常抛在 httplib 这个库上

## 使用方式

```go
var req *httplib.BeegoHTTPRequest
// ...
response, err := req.Response()

```

问题出在 `req.Response()` 上 一路跟踪过去发现问题出在 `client.go` 的 `RoundTrip` 这个方法

## 错误代码

```
goroutine 602050 [IO wait]:
internal/poll.runtime_pollWait(0x7f4d3d1a2b08, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420403c18, 0x72, 0xffffffffffffff00, 0xda7ba0, 0xda36b8)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420403c18, 0xc42046c000, 0x1000, 0x1000)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420403c00, 0xc42046c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420403c00, 0xc42046c000, 0x1000, 0x1000, 0xc420259a80, 0x4a50a1, 0xc420335780)
        /usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e008, 0xc42046c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc420165680, 0xc42046c000, 0x1000, 0x1000, 0x1000, 0x4, 0xc420259b68)
        /usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc420300060)
        /usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc420300060, 0x1, 0xc4204700c0, 0xc4204d4480, 0xc420034a80, 0xc42019e478, 0x0)
        /usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc420165680)
        /usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1186 +0xa2e
```

### 其他

```
goroutine 601943 [IO wait]:
internal/poll.runtime_pollWait(0x7f4d3d266f68, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201b0098, 0x72, 0xffffffffffffff00, 0xda7ba0, 0xda36b8)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4201b0098, 0xc420217d00, 0x1, 0x1)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4201b0080, 0xc420217db1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc4201b0080, 0xc420217db1, 0x1, 0x1, 0x1c, 0x20002, 0xc4204cffa4)
        /usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420293db8, 0xc420217db1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6d
net/http.(*connReader).backgroundRead(0xc420217da0)
        /usr/local/go/src/net/http/server.go:660 +0x62
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:656 +0xd8

goroutine 601681 [select]:
net/http.(*persistConn).roundTrip(0xc4202125a0, 0xc42007ff50, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1970 +0x608
net/http.(*Transport).RoundTrip(0xc4203a4000, 0xc420350000, 0xc4203a4000, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:413 +0x992
net/http.send(0xc420350000, 0xda5c20, 0xc4203a4000, 0x0, 0x0, 0x0, 0xc4204ac038, 0x0, 0xc4203835e8, 0x1)
        /usr/local/go/src/net/http/client.go:249 +0x1a9
net/http.(*Client).send(0xc42007fad0, 0xc420350000, 0x0, 0x0, 0x0, 0xc4204ac038, 0x0, 0x1, 0x4)
        /usr/local/go/src/net/http/client.go:173 +0xfd
net/http.(*Client).Do(0xc42007fad0, 0xc420350000, 0xa, 0xa84470, 0xb)
        /usr/local/go/src/net/http/client.go:602 +0x28d
```

**Comment by guanlicome** [comment]
Same issue to me.

**Comment by DennisMao** [comment]
@icowan 能否提供一下使用时候的示例代码

**Comment by icowan** [comment]
@DennisMao 不好意思哈，时间有点久远了，我们已经自己封装了一个httprequest

**Comment by DennisMao** [comment]
@icowan  ok,那我先关闭这个问题了

**Comment by guanlicome** [comment]
时间已经过去很久了，都忘记了。
这个问题是，虽然设置了RecoverPanic = true，只能recover在主进程中的panic, 但是在每个goroutine里面，还是需要单独处理panic。panic本身是httplib底层的，只要recover就可以。

**Comment by maxshine** [comment]
> 时间已经过去很久了，都忘记了。
> 这个问题是，虽然设置了RecoverPanic = true，只能recover在主进程中的panic, 但是在每个goroutine里面，还是需要单独处理panic。panic本身是httplib底层的，只要recover就可以。

The framework can handle panics from the http request goroutine now.
