### ISSUE TITLE
concurrent map read and map write on BeegoInput.data

### ISSUE THREAD

**Issue by wsc500www** [astaxie/beego#3366]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

> 1.9.2

2. What operating system and processor architecture are you using (`go env`)?

> GOARCH="amd64"
> GOBIN=""
> GOCHAR="6"
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> CC="gcc"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
> CXX="g++"
> CGO_ENABLED="1"

3. What did you do?
```
// router.go init()

beego.InsertFilter("/*", beego.BeforeStatic, func(ctx *context.Context) {
  ctx.Input.SetData("REQ_START_TIME", time.Now().Local())
})

beego.InsertFilter("/*", beego.FinishRouter, func(ctx *context.Context) {
  go func(ctx *context.Context) {
    startTime, ok := ctx.Input.GetData("REQ_START_TIME").(time.Time)
    if !ok {
      return
    }

    timeDur := time.Since(startTime)

    // record response time
    statsd.Rpc(ctx.Input.URL(), "<self>", timeDur, strconv.Itoa(ctx.ResponseWriter.Status))
  }(ctx)
}, false)
```

However , I got panic randomly in production 

```
fatal error: concurrent map read and map write

goroutine 24011522 [running]:
runtime.throw(0xa4752e, 0x21)
	/usr/local/go1.9.1/src/runtime/panic.go:605 +0x95 fp=0xc421bb06e8 sp=0xc421bb06c8 pc=0x42d395
runtime.mapaccess2(0x990960, 0xc4218a65a0, 0xc421bb07b8, 0xc422072120, 0x553117)
	/usr/local/go1.9.1/src/runtime/hashmap.go:413 +0x24e fp=0xc421bb0730 sp=0xc421bb06e8 pc=0x40a08e
github.com/astaxie/beego/context.(*BeegoInput).GetData(...)
	/home/scmbuild/workspaces_cluster/srm.dimension-process.git/srm/dimension-process/build-space/src/github.com/astaxie/beego/context/input.go:371
```

In input.go
```
type BeegoInput struct {
	Context     *Context
	CruSession  session.Store
	pnames      []string
	pvalues     []string
	data        map[interface{}]interface{} // store some values in this context when calling context in filter or controller.
	RequestBody []byte
}
```
Here BeegoInput.data seem to be an unsafe map. When concurrent read and write , it cause a panic.

**Comment by wsc500www** [comment]
I change BeegoInput.data to sync.Map , but still got panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x46fe23]

goroutine 10611781 [running]:
sync.(*Map).Load(0xc423fa8e08, 0x965280, 0xaad3a0, 0x0, 0x0, 0x66eb0ea)
	/usr/local/go1.9.1/src/sync/map.go:102 +0x93
github.com/astaxie/beego/context.(*BeegoInput).GetData(0xc423fa8dc0, 0x965280, 0xaad3a0, 0x6, 0x66eb0ea)
```
