### ISSUE TITLE
Generating docs fails when passing variable to NSInclude

### ISSUE THREAD

**Issue by alon-abadi** [astaxie/beego#3558]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
├── Beego     : 1.9.2
├── GoVersion : go1.10.1
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/alon/gopath
├── GOROOT    : /usr/local/Cellar/go/1.10.1/libexec
├── Compiler  : gc
└── Date      : Monday, 4 Mar 2019
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alon/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alon/gopath"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t6/9l65y0js33nd31xxn8755vv80000gn/T/go-build382808289=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

ran `bee generate docs`, that fails, and complains about interface conversion: 

```
panic: interface conversion: ast.Expr is *ast.CallExpr, not *ast.UnaryExpr

goroutine 1 [running]:
github.com/beego/bee/generate/swaggergen.analyseNSInclude(0xc420210c0c, 0x3, 0xc4200cd840, 0xc4203e5b40, 0x2)
	/Users/alon/gopath/src/github.com/beego/bee/generate/swaggergen/g_docs.go:361 +0xa5f
github.com/beego/bee/generate/swaggergen.GenerateDocs(0xc4200240a4, 0x3d)
	/Users/alon/gopath/src/github.com/beego/bee/generate/swaggergen/g_docs.go:287 +0x2034
github.com/beego/bee/cmd/commands/generate.GenerateCode(0x499eb80, 0xc42001e160, 0x2, 0x2, 0x2)
	/Users/alon/gopath/src/github.com/beego/bee/cmd/commands/generate/generate.go:98 +0x396
main.main()
	/Users/alon/gopath/src/github.com/beego/bee/main.go:75 +0x2a3
```

relevant part in router: 
```
featureController := v1.NewFeaturesController(
		orchestrator.NewFeatureOrchestrator(
			store.NewFeatureSegmentPSQL()))

	apiV1 := beego.NewNamespace("/api",
		beego.NSNamespace("/v1",
			beego.NSInclude(
				featureController,
```
when I change it to this, it works: 

```
apiV1 := beego.NewNamespace("/api",
		beego.NSNamespace("/v1",
			beego.NSInclude(
				v1.NewFeaturesController(
					orchestrator.NewFeatureOrchestrator(
						store.NewFeatureSegmentPSQL())),
```

4. What did you expect to see?

0007 Docs successfully generated!

5. What did you see instead?

```
panic: interface conversion: ast.Expr is *ast.CallExpr, not *ast.UnaryExpr

goroutine 1 [running]:
github.com/beego/bee/generate/swaggergen.analyseNSInclude(0xc420210c0c, 0x3, 0xc4200cd840, 0xc4203e5b40, 0x2)
	/Users/alon/gopath/src/github.com/beego/bee/generate/swaggergen/g_docs.go:361 +0xa5f
github.com/beego/bee/generate/swaggergen.GenerateDocs(0xc4200240a4, 0x3d)
	/Users/alon/gopath/src/github.com/beego/bee/generate/swaggergen/g_docs.go:287 +0x2034
github.com/beego/bee/cmd/commands/generate.GenerateCode(0x499eb80, 0xc42001e160, 0x2, 0x2, 0x2)
	/Users/alon/gopath/src/github.com/beego/bee/cmd/commands/generate/generate.go:98 +0x396
main.main()
	/Users/alon/gopath/src/github.com/beego/bee/main.go:75 +0x2a3
```

**Comment by alon-abadi** [comment]
update: looks like when I use short variable declaration, it doesn't work, and otherwise it does.

Setting the controller using `var` and using plain assignment `=` works fine, and also neglecting the variable and using `NewFeaturesController( ... )` directly works. It's only when I use short declaration (`:=`) I get the panic.
