### ISSUE TITLE
Beego parse parameter  "fatal error: concurrent map read and map write"

### ISSUE THREAD

**Issue by Anderson-Lu** [astaxie/beego#3686]
Beego高并发下参数解析会崩溃"fatal error: concurrent map read and map write"
---

1. bee version如下：

```shell
➜  demo git:(demo) ✗ bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

├── Beego     : 1.11.1
├── GoVersion : go1.12
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 6
├── GOPATH    : /data/workspace
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Saturday, 15 Jun 2019
```

2. 使用的环境如下

```shell
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/anderson/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/workspace"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build138663340=/tmp/go-build -gno-record-gcc-switches"
```

3. 代码中使用beego自带的参数解析方法获取参数

```golang
type AdBaseController struct {
	beego.Controller
}

//通过beego自带的GetString()方法获取请求参数
func (this *AdBaseController) getAdRequestFromClient() string{	
	platform := this.GetString("platform", models.PLATFORM_ANDROID)
        return platform
}
```

4. What did you expect to see?

正常情况下不应该报错

5. What did you see instead?

实际情况下，QPS(>=10000)较高时, 出现并发异常，程序奔溃, 主要日志如下：

```log
   /usr/local/go1.12.2/go/src/runtime/panic.go:617 +0x72 fp=0xc060f2ecd8 sp=0xc060f2eca8 pc=0x42f3e2
 fatal error: concurrent map read and map write
 runtime.throw(0xd47c38, 0x21)
 goroutine 116873 [running]:
 vendor/github.com/astaxie/beego/context.(*BeegoInput).Query(0xc036902320, 0xd2b49a, 0x2, 0xc029124f80, 0xc029124f80)
   /data/build/mo_server/service-ad-adapter/master/1560516101/gopath/src/ad-adapter/controllers/ad_base_ctl.go:51 +0x83f fp=0xc060f2f098 sp=0xc060f2edb8 pc=0xb10a0f
 net/http.serverHandler.ServeHTTP(0xc007e0fc70, 0xe62b20, 0xc01fb708c0, 0xc0557d7a00)
   /usr/local/go1.12.2/go/src/net/url/url.go:838
   /usr/local/go1.12.2/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc060f2ffd0 sp=0xc060f2ffc8 pc=0x45c951
 ad-adapter/controllers.(*AdBaseController).getAdRequestFromClient(0xc02d637a40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
   /data/build/mo_server/service-ad-adapter/master/1560516101/gopath/src/vendor/github.com/astaxie/beego/app.go:159 +0x3a1
   /data/build/mo_server/service-ad-adapter/master/1560516101/gopath/src/vendor/github.com/astaxie/beego/router.go:829 +0x255b fp=0xc060f2fcf0 sp=0xc060f2f628 pc=0x8b270b
 goroutine 5 [syscall, 4 minutes]:
 runtime.goexit()
```

具体位置是**github.com/astaxie/beego/context/input.go:328**

```golang
// Query returns input data item string by a given string.
func (input *BeegoInput) Query(key string) string {
	if val := input.Param(key); val != "" {
		return val
	}
	if input.Context.Request.Form == nil {
		input.Context.Request.ParseForm()
	}
	return input.Context.Request.Form.Get(key) //这里会直接导致并发map读写使程序崩溃
}
```

**Comment by clia** [comment]
我们也遇到了这样的问题：
```
fatal error: concurrent map writes

goroutine 173649579 [running]:
runtime.throw(0xe44283, 0x15)
	D:/programme/Go/src/runtime/panic.go:617 +0x72 fp=0xc001cdd700 sp=0xc001cdd6d0 pc=0x42d692
runtime.mapassign_faststr(0xd9b9e0, 0xc00de929f0, 0xc00028ed46, 0x2, 0xc001cffe40)
	D:/programme/Go/src/runtime/map_faststr.go:211 +0x42a fp=0xc001cdd768 sp=0xc001cdd700 pc=0x412e0a
net/url.Values.Add(...)
	D:/programme/Go/src/net/url/url.go:854
net/http.copyValues(0xc00de929f0, 0xc00de92a20)
	D:/programme/Go/src/net/http/request.go:1125 +0xe1 fp=0xc001cdd858 sp=0xc001cdd768 pc=0x6c7141
net/http.(*Request).ParseForm(0xc001e5c600, 0x21, 0xe42392)
	D:/programme/Go/src/net/http/request.go:1223 +0xf1 fp=0xc001cdd8d8 sp=0xc001cdd858 pc=0x6c77c1
github.com/astaxie/beego/context.(*BeegoInput).ParseFormOrMulitForm(0xc008f69b90, 0x4000000, 0xc001689c00, 0x26)
	D:/gopath/src/github.com/astaxie/beego/context/input.go:410 +0x18e fp=0xc001cdd940 sp=0xc001cdd8d8 pc=0x7fc13e
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc0000b64d0, 0xf8d200, 0xc009295960, 0xc001e5c600)
	D:/gopath/src/github.com/astaxie/beego/router.go:712 +0xbbd fp=0xc001cddcf0 sp=0xc001cdd940 pc=0x8cfb1d
net/http.serverHandler.ServeHTTP(0xc0004051e0, 0xf8d200, 0xc009295960, 0xc001e5c600)
	D:/programme/Go/src/net/http/server.go:2774 +0xa8 fp=0xc001cddd20 sp=0xc001cddcf0 pc=0x6d5b18
net/http.(*conn).serve(0xc00e448b40, 0xf90c80, 0xc00e1358c0)
	D:/programme/Go/src/net/http/server.go:1878 +0x851 fp=0xc001cddfc8 sp=0xc001cddd20 pc=0x6d1801
runtime.goexit()
	D:/programme/Go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc001cddfd0 sp=0xc001cddfc8 pc=0x45aa21
created by net/http.(*Server).Serve
	D:/programme/Go/src/net/http/server.go:2884 +0x2f4
```

**Comment by Paxa** [comment]
ничего не понятно
