### ISSUE TITLE
panic: reflect: call of reflect.Value.Interface on zero Value

### ISSUE THREAD

**Issue by 1000Delta** [astaxie/beego#3694]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```bash
├── Beego     : 1.11.2
├── GoVersion : go1.12.5
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Users\13975\go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Wednesday, 19 Jun 2019
```

2. What operating system and processor architecture are you using (`go env`)?
```bash
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\13975\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\13975\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\13975\AppData\Local\Temp\go-build937066154=/tmp/go-build -gno-record-gcc-switches
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```go
package models

import (
	"fmt"

	"github.com/astaxie/beego"
	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

func init() {

	orm.RegisterDriver("mysql", orm.DRMySQL)
	orm.RegisterDataBase("default", "mysql", beego.AppConfig.String("sqlconn"))
	orm.RegisterModel(
		new(Student), new(Teacher), new(User), // 用户数据
		new(Demand), new(Reservation), new(OrderInfo), // 事件数据
		new(Location), new(Institution), new(Grade), new(Subject), // 公共数据
	)
	name := "default" // 数据库别名
	force := true     // drop table后再建表
	verbose := true   // 打印执行过程
	err := orm.RunSyncdb(name, force, verbose)
	if err != nil {
		fmt.Println(err)
	}
}
```

4. What did you expect to see?
成功注册模型并创建数据表

5. What did you see instead?
```bash
panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 1 [running]:
reflect.valueInterface(0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        C:/Go/src/reflect/value.go:984 +0x1a8
reflect.Value.Interface(...)
        C:/Go/src/reflect/value.go:979
github.com/astaxie/beego/orm.getFieldType(0x95bf60, 0xc0000e64a8, 0x196, 0x7, 0xf335c0, 0x0)
        C:/Users/13975/go/src/github.com/astaxie/beego/orm/models_utils.go:182 +0x6bf
github.com/astaxie/beego/orm.newFieldInfo(0xc00005d540, 0x95bf60, 0xc0000e64a8, 0x196, 0x955eeb, 0xb, 0x0, 0x0, 0xb38740, 0x95bf60, ...)
        C:/Users/13975/go/src/github.com/astaxie/beego/orm/models_info_f.go:244 +0x26cc
github.com/astaxie/beego/orm.addModelFields(0xc00005d540, 0xa20c40, 0xc0000e6480, 0x199, 0x0, 0x0, 0xc00008bbb8, 0x0, 0x0)
        C:/Users/13975/go/src/github.com/astaxie/beego/orm/models_info_m.go:70 +0x3be
github.com/astaxie/beego/orm.newModelInfo(0x9a3200, 0xc0000e6480, 0x16, 0x14)
        C:/Users/13975/go/src/github.com/astaxie/beego/orm/models_info_m.go:45 +0x22f
github.com/astaxie/beego/orm.registerModel(0x0, 0x0, 0x9a3200, 0xc0000e6480, 0x1)
        C:/Users/13975/go/src/github.com/astaxie/beego/orm/models_boot.go:62 +0x37d
github.com/astaxie/beego/orm.RegisterModelWithPrefix(0x0, 0x0, 0xc00008bec8, 0xa, 0xa)
        C:/Users/13975/go/src/github.com/astaxie/beego/orm/models_boot.go:320 +0x92
github.com/astaxie/beego/orm.RegisterModel(0xc00008bec8, 0xa, 0xa)
        C:/Users/13975/go/src/github.com/astaxie/beego/orm/models_boot.go:310 +0x5f
TeachBackBee/models.init.0()
        C:/Users/13975/go/src/TeachBackBee/models/models.go:15 +0x342
```

**Comment by 1000Delta** [comment]
解决问题了，数据表关系一定要设置好`reverse`，不然无法建立
