### ISSUE TITLE
Execution orm func One(),panic: reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by helloqhq** [astaxie/beego#4127]
```
func GetCampaignWithAppByIdAndUid(cid uint64, cols ...string) (res *A, err error) {
	o := orm.NewOrm()
	err = o.QueryTable("a").
		Filter("ID", cid).
		One(res, cols...)
	if err != nil {
		return nil, err
	}

	return res, err
}
```

panic info

```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 77 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:1884 +0x166
github.com/astaxie/beego/orm.(*dbBase).ReadBatch(0xc000033f70, 0x10a5460, 0xc0000c7f00, 0xc00022aaa0, 0xc00022a5a0, 0xc00000ebc0, 0xdbf780, 0x0, 0x174d9e0, 0xc00010a000, ...)
        /data/www/go/pkg/mod/github.com/astaxie/beego@v1.12.2/orm/db.go:944 +0x2b01
github.com/astaxie/beego/orm.(*querySet).One(0xc00022aaa0, 0xdbf780, 0x0, 0xc00010a000, 0x13, 0x13, 0x10b1680, 0xc00022aaa0)
        /data/www/go/pkg/mod/github.com/astaxie/beego@v1.12.2/orm/orm_queryset.go:226 +0xbf

```

**Comment by flycash** [comment]
Could you please share your table schema and this table's data? I need them to reproduce the bug

**Comment by flycash** [comment]
And what's the version do you use?

**Comment by helloqhq** [comment]
> And what's the version do you use?

1.11

**Comment by helloqhq** [comment]
> Could you please share your table schema and this table's data? I need them to reproduce the bug

Should have nothing to do with table structure and data
After res is changed to slice, it is normal

```
func GetCampaignWithAppByIdAndUid(cid uint64, cols ...string) (res []*A, err error) {
	o := orm.NewOrm()
	err = o.QueryTable("a").
		Filter("ID", cid).
		One(res, cols...)
	if err != nil {
		return nil, err
	}

	return res, err
}
```
